import { signal } from '@angular/core';
import type { SiteContent } from './site-content.models';

export const SITE_CONTENT = {
  name: '台灣微生物學會',
  website: 'www.microbiologytw.org.tw',
  navigation: [
    { key: 'about', label: '關於本會', href: '#about' },
    { key: 'news', label: '最新消息', href: '#news' },
    { key: 'events', label: '學術活動', href: '#events' },
    { key: 'resources', label: '期刊資源', href: '#resources' },
    { key: 'membership', label: '會員專區', href: '#membership' },
  ],
  hero: {
    title: '探索微觀，連結更健康的未來',
    description: '透過深化微生物科學的探索與創新，推動疾病防治、新藥研發與生態永續發展，共同攜手引領微生物學界的卓越成長，邁向國際永續新視野。',
    primaryAction: { label: '查看學術活動', href: '#events' },
    secondaryAction: { label: '會員登入', href: '#membership' },
  },
  quickAccess: [
    {
      key: 'news',
      title: '最新消息',
      description: '2026 年度會員大會資訊',
      label: '查看消息',
      href: '#news',
      symbol: 'newspaper',
    },
    {
      key: 'events',
      title: '學術活動',
      description: '微生物學年度研討會',
      label: '立即報名',
      href: '#events',
      symbol: 'science',
    },
    {
      key: 'membership',
      title: '會員服務',
      description: '會費與活動紀錄',
      label: '前往會員專區',
      href: '#membership',
      symbol: 'groups',
    },
  ],
  events: [
    {
      key: 'annual-meeting',
      eyebrow: '近期研討會',
      title: '2026 微生物學年度研討會',
      meta: '2026.11.14-15｜臺北',
      primaryAction: { label: '立即報名', href: '#registration' },
      secondaryAction: { label: '查看活動資訊', href: '#event-detail' },
    },
    {
      key: 'paper-submission',
      eyebrow: '學術論文投稿',
      title: '會員大會學術論文投稿',
      meta: '投稿截止｜2026.10.02',
      primaryAction: { label: '申請投稿', href: '#submission' },
      secondaryAction: { label: '下載投稿說明', href: '#submission-guide' },
    },
  ],
  news: [
    {
      key: 'assembly-registration',
      category: '學會公告',
      date: '2026.08.28',
      title: '2026 年度會員大會報名開放',
      href: '#news-assembly',
      image: 'latest-news',
    },
    {
      key: 'annual-call',
      category: '學術活動',
      date: '2026.08.15',
      title: '微生物學年度研討會徵稿公告',
      href: '#news-call',
      image: 'academic-events',
    },
    {
      key: 'membership-fee',
      category: '會員通知',
      date: '2026.08.01',
      title: '年度會費繳納與電子收據說明',
      href: '#news-fee',
      image: 'membership',
    },
  ],
  resources: [
    {
      key: 'journal',
      title: '微免與感染雜誌',
      description: 'Journal of Microbiology, Immunology and Infection',
      label: '前往期刊網站',
      href: 'https://jmii.org/',
      external: true,
      symbol: 'description',
    },
    {
      key: 'scholarship',
      title: '獎學金申請',
      description: '嚴智鍾教授獎學金申請',
      label: '查看申請資訊',
      href: '#scholarship',
      external: false,
      symbol: 'school',
    },
    {
      key: 'constitution',
      title: '組織章程',
      description: '本會組織、理監事會與委員會資訊',
      label: '閱讀章程',
      href: '#constitution',
      external: false,
      symbol: 'article',
    },
    {
      key: 'about',
      title: '本會介紹',
      description: '認識台灣微生物學會',
      label: '認識本會',
      href: '#about',
      external: false,
      symbol: 'biotech',
    },
  ],
  memberActions: [
    {
      key: 'login',
      title: '會員登入',
      label: '登入帳戶',
      href: '#login',
      symbol: 'login',
      emphasis: 'primary',
    },
    {
      key: 'register',
      title: '新會員申請',
      label: '立即申請',
      href: '#register',
      symbol: 'person_add',
      emphasis: 'secondary',
    },
    {
      key: 'fee',
      title: '會費查詢',
      label: '查詢會費',
      href: '#fees',
      symbol: 'receipt_long',
      emphasis: 'tertiary',
    },
    {
      key: 'activity-history',
      title: '參與活動列表',
      label: '查看紀錄',
      href: '#activity-history',
      symbol: 'calendar_month',
      emphasis: 'tertiary',
    },
  ],
} as const satisfies SiteContent;

export const siteContent = signal(SITE_CONTENT).asReadonly();
