import { signal } from '@angular/core';
import type { SiteContent } from './site-content.models';

export const SITE_CONTENT = {
  name: '台灣微生物學會',
  website: 'www.microbiologytw.org.tw',
  navigation: [
    { key: 'about', label: '關於本會', href: '#about' },
    { key: 'news', label: '最新消息', href: '#news' },
    { key: 'events', label: '學術活動', href: '#events' },
    { key: 'resources', label: '期刊資源', href: '#resources' },
    { key: 'membership', label: '會員專區', href: '#membership' },
  ],
  hero: {
    title: '微觀世界，守護更健康的未來',
    description: '透過深化微生物科學的探索與創新，推動疾病防治、新藥研發與生態永續發展，共同攜手引領微生物學界的卓越成長，邁向國際永續新視野。',
    primaryAction: { label: '查看學術活動', href: '#events' },
    secondaryAction: { label: '會員登入', href: '#membership' },
  },
  quickAccess: [
    {
      key: 'news',
      title: '最新消息',
      description: '掌握學會公告、重要更新與微生物領域相關焦點資訊。',
      label: '查看消息',
      href: '#news',
      symbol: 'newspaper',
    },
    {
      key: 'events',
      title: '學術活動',
      description: '瀏覽研討會、工作坊與各類學術活動，掌握重要會議時程。',
      label: '立即報名',
      href: '#events',
      symbol: 'science',
    },
    {
      key: 'membership',
      title: '會員服務',
      description: '提供會員專屬資源與服務，促進學術交流與專業發展。',
      label: '前往會員專區',
      href: '#membership',
      symbol: 'groups',
    },
  ],
  events: [
    {
      key: 'annual-meeting',
      eyebrow: '近期研討會',
      title: '2026 微生物學年度研討會',
      meta: '2026.11.14-15｜臺北',
      bDateRail: { year: '2026', date: '11.14', day: 'SAT' },
      bDescription: '串聯研究者與臨床專家，分享微生物學研究的新觀點。',
      primaryAction: { label: '立即報名', href: '#registration' },
      secondaryAction: { label: '查看活動資訊', href: '#event-detail' },
    },
    {
      key: 'paper-submission',
      eyebrow: '學術論文投稿',
      title: '會員大會學術論文投稿',
      meta: '投稿截止｜2026.10.02',
      bDateRail: { year: '2026', date: '10.02', day: 'FRI' },
      bDescription: '邀請會員發表最新研究成果，深化跨領域的學術交流。',
      primaryAction: { label: '申請投稿', href: '#submission' },
      secondaryAction: { label: '下載投稿說明', href: '#submission-guide' },
    },
  ],
  bReference: {
    eventsLead: '掌握研討交流、投稿時程與微生物學界的重要學術資訊。',
    eventsArchive: { label: '查看所有活動', href: '#events-list' },
    eventsCaption: 'ADVANCING MICROBIAL SCIENCE FOR A HEALTHIER TOMORROW',
    eventsCaptionMeta: 'Research · Collaboration · Impact',
    resourcesLead: '提供會員與相關領域專業人士取得學術資訊、申請資源及了解本會運作的完整管道。',
    newsLead: '掌握學會公告、研究交流與近期學術動態。',
    membershipHeading: '會員專區服務',
  },
  news: [
    {
      key: 'assembly-registration',
      category: '學會公告',
      date: '2026.08.28',
      title: '2026 年度會員大會報名開放',
      summary: '年度會員大會即日起開放報名，邀請會員共聚交流。',
      href: '#news-assembly',
      image: 'latest-news',
    },
    {
      key: 'annual-call',
      category: '學術活動',
      date: '2026.08.15',
      title: '微生物學年度研討會徵稿公告',
      summary: '徵集微生物學研究成果，與各領域專家共享新知。',
      href: '#news-call',
      image: 'academic-events',
    },
    {
      key: 'membership-fee',
      category: '會員通知',
      date: '2026.08.01',
      title: '年度會費繳納與電子收據說明',
      summary: '了解繳費方式與電子收據申請流程，完成年度會員服務。',
      href: '#news-fee',
      image: 'membership',
    },
  ],
  resources: [
    {
      key: 'journal',
      title: '微免與感染雜誌',
      description: '提供微生物學與感染症領域之最新研究成果與學術交流平台。',
      label: '前往期刊網站',
      href: 'https://jmii.org/',
      external: true,
      symbol: 'description',
    },
    {
      key: 'scholarship',
      title: '獎學金申請',
      description: '協助培育微生物相關領域之優秀人才，提供獎學金申請資訊與辦法。',
      label: '查看申請資訊',
      href: '#scholarship',
      external: false,
      symbol: 'school',
    },
    {
      key: 'constitution',
      title: '組織章程',
      description: '查閱本會章程、組織架構及相關規範，瞭解本會運作機制。',
      label: '閱讀章程',
      href: '#constitution',
      external: false,
      symbol: 'article',
    },
    {
      key: 'about',
      title: '本會介紹',
      description: '認識台灣微生物學會的宗旨、發展歷程與主要業務。',
      label: '認識本會',
      href: '#about',
      external: false,
      symbol: 'biotech',
    },
  ],
  memberActions: [
    {
      key: 'login',
      bDescription: '登入會員帳號，享有專屬會員服務與最新資訊。',
      title: '會員登入',
      label: '登入帳戶',
      href: '#login',
      symbol: 'login',
      emphasis: 'primary',
    },
    {
      key: 'register',
      bDescription: '歡迎加入台灣微生物學會，申請成為會員並開啟更多交流與學習機會。',
      title: '新會員申請',
      label: '立即申請',
      href: '#register',
      symbol: 'person_add',
      emphasis: 'secondary',
    },
    {
      key: 'fee',
      bDescription: '查詢個人會費繳納紀錄與繳費狀態。',
      title: '會費查詢',
      label: '查詢會費',
      href: '#fees',
      symbol: 'receipt_long',
      emphasis: 'tertiary',
    },
    {
      key: 'activity-history',
      bDescription: '瀏覽學會最新活動、研討會與學術會議，掌握重要時程。',
      title: '參與活動列表',
      label: '查看紀錄',
      href: '#activity-history',
      symbol: 'calendar_month',
      emphasis: 'tertiary',
    },
  ],
} as const satisfies SiteContent;

export const siteContent = signal(SITE_CONTENT).asReadonly();
